### <center>Indian Institute of Management Ahmedabad</center>
#### <center>Machine Learning with Big Data: Assignment 2</center>
<center>ePGD ABA 2021-22</center>

<font color = "purple"><center>Submitted by : <br>
    Group 8 <br>
    Monica Yadav <br>
    Shubhanjali Sharma <br>
    Shivam Singh</center></font>

<b> Question 4.2 Principal Component Analysis </b>

<b> <font color='purple'>Importing the Libraries & dataset </font> </b>

In [2]:
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pylab as plt

import dmba

%matplotlib inline

In [4]:
university_dataset = pd.read_csv("D:/Monica/IIMA ABA/Modules/Machine Learning/Assignment 2/Universities.csv")
university_dataset.head(5)

,College Name,State,Public (1)/ Private (2),# appli. rec'd,# appl. accepted,# new stud. enrolled,% new stud. from top 10%,% new stud. from top 25%,# FT undergrad,# PT undergrad,in-state tuition,out-of-state tuition,room,board,add. fees,estim. book costs,estim. personal $,% fac. w/PHD,stud./fac. ratio,Graduation rate
0,Alaska Pacific University,AK,2,193.0,146.0,55.0,16.0,44.0,249.0,869.0,7560.0,7560.0,1620.0,2500.0,130.0,800.0,1500.0,76.0,11.9,15.0
1,University of Alaska at Fairbanks,AK,1,1852.0,1427.0,928.0,NaN,NaN,3885.0,4519.0,1742.0,5226.0,1800.0,1790.0,155.0,650.0,2304.0,67.0,10.0,NaN
2,University of Alaska Southeast,AK,1,146.0,117.0,89.0,4.0,24.0,492.0,1849.0,1742.0,5226.0,2514.0,2250.0,34.0,500.0,1162.0,39.0,9.5,39.0
3,University of Alaska at Anchorage,AK,1,2065.0,1598.0,1162.0,NaN,NaN,6209.0,10537.0,1742.0,5226.0,2600.0,2520.0,114.0,580.0,1260.0,48.0,13.7,NaN
4,Alabama Agri. & Mech. Univ.,AL,1,2817.0,1920.0,984.0,NaN,NaN,3958.0,305.0,1700.0,3400.0,1108.0,1442.0,155.0,500.0,850.0,53.0,14.3,40.0

<b> <font color='purple'>Part A : Removing the Categorical and Missing Data  </font></b>

In [5]:
cleaned_df1 = university_dataset[university_dataset.columns[3:20]]
cleaned_df = cleaned_df1.dropna()
cleaned_df

,# appli. rec'd,# appl. accepted,# new stud. enrolled,% new stud. from top 10%,% new stud. from top 25%,# FT undergrad,# PT undergrad,in-state tuition,out-of-state tuition,room,board,add. fees,estim. book costs,estim. personal $,% fac. w/PHD,stud./fac. ratio,Graduation rate
0,193.0,146.0,55.0,16.0,44.0,249.0,869.0,7560.0,7560.0,1620.0,2500.0,130.0,800.0,1500.0,76.0,11.9,15.0
2,146.0,117.0,89.0,4.0,24.0,492.0,1849.0,1742.0,5226.0,2514.0,2250.0,34.0,500.0,1162.0,39.0,9.5,39.0
9,805.0,588.0,287.0,67.0,88.0,1376.0,207.0,11660.0,11660.0,2050.0,2430.0,120.0,400.0,900.0,74.0,14.0,72.0
11,608.0,520.0,127.0,26.0,47.0,538.0,126.0,8080.0,8080.0,1380.0,2540.0,100.0,500.0,1100.0,63.0,11.4,44.0
21,4414.0,1500.0,335.0,30.0,60.0,908.0,119.0,5666.0,5666.0,1424.0,1540.0,418.0,1000.0,1400.0,56.0,15.5,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274,5729.0,4520.0,1957.0,20.0,52.0,8516.0,1264.0,2208.0,6996.0,1565.0,1140.0,1070.0,279.0,1260.0,80.0,19.3,61.0
1283,152.0,128.0,75.0,17.0,41.0,282.0,22.0,9100.0,9100.0,1800.0,1900.0,90.0,500.0,1400.0,48.0,8.5,50.0
1284,582.0,498.0,172.0,21.0,44.0,799.0,78.0,10468.0,10468.0,1574.0,1806.0,92.0,660.0,1800.0,40.0,11.5,52.0
1291,4226.0,3666.0,2007.0,14.0,60.0,7703.0,2339.0,1660.0,5094.0,2030.0,1980.0,330.0,700.0,1560.0,77.0,16.6,50.0
1301,2029.0,1516.0,1073.0,23.0,46.0,7535.0,1488.0,1908.0,5988.0,1462.0,1960.0,300.0,600.0,1500.0,91.0,15.1,45.0

<b> <font color='purple'>Data Summary  </font></b>

In [14]:
pd.DataFrame({'mean': cleaned_df.mean(),
              'sd': cleaned_df.std(),
              'min': cleaned_df.min(),
              'max': cleaned_df.max(),
              'median': cleaned_df.median(),
              'length': len(cleaned_df),
              'miss.val': cleaned_df.isnull().sum(),
             })

,mean,sd,min,max,median,length,miss.val
# appli. rec'd,3147.303609,4073.138136,77.0,48094.0,1646.0,471,0
# appl. accepted,2062.955414,2503.752754,61.0,26330.0,1227.0,471,0
# new stud. enrolled,780.704883,915.633300,27.0,6392.0,443.0,471,0
% new stud. from top 10%,28.012739,18.479196,1.0,96.0,23.0,471,0
% new stud. from top 25%,55.651805,20.324333,9.0,100.0,54.0,471,0
# FT undergrad,3562.938429,4669.226389,249.0,31643.0,1715.0,471,0
# PT undergrad,797.454352,1545.796419,1.0,21836.0,299.0,471,0
in-state tuition,9406.634820,5516.794516,608.0,20100.0,9858.0,471,0
out-of-state tuition,10575.161359,4311.672049,1044.0,20100.0,10100.0,471,0
room,2221.108280,713.188110,640.0,4816.0,2090.0,471,0
board,2121.940552,566.861037,531.0,4541.0,2082.0,471,0
add. fees,379.021231,355.855253,10.0,3247.0,280.0,471,0
estim. book costs,548.783439,163.185575,90.0,2340.0,500.0,471,0
estim. personal $,1311.940552,681.847238,250.0,6800.0,1200.0,471,0
% fac. w/PHD,73.208068,16.665649,8.0,103.0,76.0,471,0
stud./fac. ratio,13.962633,3.898855,2.9,28.8,13.4,471,0
Graduation rate,65.562633,18.146912,15.0,118.0,66.0,471,0

<b> <font color='purple'>Part B : PCA  </font></b>

In [23]:
pcs = PCA()
pcs.fit(cleaned_df.dropna(axis=0))
pcsSummary_df = pd.DataFrame({'Standard deviation': np.sqrt(pcs.explained_variance_),
                           'Proportion of variance': pcs.explained_variance_ratio_,
                           'Cumulative proportion': np.cumsum(pcs.explained_variance_ratio_)})
pcsSummary_df = pcsSummary_df.transpose()
pcsSummary_df.columns = ['PC{}'.format(i) for i in range(1, len(pcsSummary_df.columns) + 1)]
pcsSummary_df.round(4)

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17
Standard deviation,7430.9140,5987.9890,1854.6412,1192.5293,967.4279,679.6527,596.9761,580.6299,417.6136,318.1272,188.8676,155.6062,19.0491,12.5287,11.0184,5.33,2.9059
Proportion of variance,0.5614,0.3645,0.0350,0.0145,0.0095,0.0047,0.0036,0.0034,0.0018,0.0010,0.0004,0.0002,0.0000,0.0000,0.0000,0.00,0.0000
Cumulative proportion,0.5614,0.9259,0.9609,0.9753,0.9848,0.9895,0.9932,0.9966,0.9984,0.9994,0.9997,1.0000,1.0000,1.0000,1.0000,1.00,1.0000

<b> <font color='purple'> Without normalising data, we can capture 92% variability with PC1 and PC2. But since the variables are in different units (eg: dollars, percentages, numbers, etc.) it is best to normalise so that they are comparable. Performing PCA on un-normalized variables will lead to insanely large loadings for variables with high variance. In turn, this will lead to dependence of a principal component on the variable with high variance. This is undesirable. </font></b>

<b> <font color='purple'> Normalising data </font></b>

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(cleaned_df)
y = sc.transform(cleaned_df)

normalised_data = pd.DataFrame(y, columns = cleaned_df.columns)
normalised_data

,# appli. rec'd,# appl. accepted,# new stud. enrolled,% new stud. from top 10%,% new stud. from top 25%,# FT undergrad,# PT undergrad,in-state tuition,out-of-state tuition,room,board,add. fees,estim. book costs,estim. personal $,% fac. w/PHD,stud./fac. ratio,Graduation rate
0,-0.726085,-0.766447,-0.793414,-0.650759,-0.573903,-0.710495,0.046333,-0.335086,-0.700046,-0.843743,0.667644,-0.700526,1.541090,0.276102,0.167704,-0.529598,-2.789257
1,-0.737636,-0.778042,-0.756242,-1.300829,-1.558991,-0.658397,0.680985,-1.390805,-1.241943,0.411116,0.226150,-0.970586,-0.299262,-0.220137,-2.054792,-1.145818,-1.465311
2,-0.575673,-0.589724,-0.539768,2.112035,1.593292,-0.468871,-0.382380,0.408890,0.251873,-0.240175,0.544026,-0.728658,-0.912713,-0.604796,0.047569,0.009594,0.355113
3,-0.624090,-0.616912,-0.714697,-0.109035,-0.426140,-0.648535,-0.434836,-0.240728,-0.579315,-1.180618,0.738283,-0.784920,-0.299262,-0.311163,-0.613173,-0.657977,-1.189489
4,0.311318,-0.225084,-0.487290,0.107655,0.214168,-0.569208,-0.439369,-0.678766,-1.139785,-1.118857,-1.027693,0.109652,2.767992,0.129286,-1.033645,0.394732,-1.079161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,0.634509,0.982388,1.286045,-0.434070,-0.179868,1.061916,0.302137,-1.306246,-0.830992,-0.920943,-1.734084,1.943806,-1.654989,-0.076257,0.407974,1.370413,-0.251695
467,-0.736162,-0.773644,-0.771548,-0.596587,-0.721666,-0.703420,-0.502187,-0.055641,-0.342496,-0.591087,-0.391942,-0.813051,-0.299262,0.129286,-1.514185,-1.402576,-0.858503
468,-0.630480,-0.625708,-0.665498,-0.379897,-0.573903,-0.592577,-0.465921,0.192593,-0.024880,-0.908311,-0.557944,-0.807425,0.682259,0.716551,-1.994724,-0.632301,-0.748174
469,0.265113,0.640938,1.340710,-0.759104,0.214168,0.887612,0.998310,-1.405684,-1.272590,-0.268248,-0.250664,-0.137903,0.927639,0.364192,0.227772,0.677166,-0.858503
470,-0.274848,-0.218687,0.319567,-0.271552,-0.475394,0.851594,0.447200,-1.360683,-1.065025,-1.065519,-0.285983,-0.222296,0.314188,0.276102,1.068716,0.292028,-1.134325

In [25]:
normalised_data.describe().round(2)

,# appli. rec'd,# appl. accepted,# new stud. enrolled,% new stud. from top 10%,% new stud. from top 25%,# FT undergrad,# PT undergrad,in-state tuition,out-of-state tuition,room,board,add. fees,estim. book costs,estim. personal $,% fac. w/PHD,stud./fac. ratio,Graduation rate
count,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00,471.00
mean,0.00,0.00,0.00,-0.00,-0.00,-0.00,0.00,0.00,0.00,-0.00,-0.00,0.00,0.00,0.00,0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-0.75,-0.80,-0.82,-1.46,-2.30,-0.71,-0.52,-1.60,-2.21,-2.22,-2.81,-1.04,-2.81,-1.56,-3.92,-2.84,-2.79
25%,-0.58,-0.57,-0.56,-0.70,-0.77,-0.55,-0.46,-1.04,-0.76,-0.68,-0.66,-0.68,-0.30,-0.68,-0.61,-0.68,-0.69
50%,-0.37,-0.33,-0.37,-0.27,-0.08,-0.40,-0.32,0.08,-0.11,-0.18,-0.07,-0.28,-0.30,-0.16,0.17,-0.14,0.02
75%,0.18,0.16,0.13,0.43,0.66,0.11,0.05,0.70,0.63,0.62,0.53,0.30,0.31,0.42,0.83,0.64,0.74
max,11.05,9.70,6.13,3.68,2.18,6.02,13.62,1.94,2.21,3.64,4.27,8.07,10.99,8.06,1.79,3.81,2.89

<b> <font color='purple'> The above data is normalised as the mean = 0  and sd = 1  </font></b>

In [26]:
pcs = PCA()
pcs.fit(normalised_data)
pcsSummary_df = pd.DataFrame({'Standard deviation': np.sqrt(pcs.explained_variance_),
                           'Proportion of variance': pcs.explained_variance_ratio_,
                           'Cumulative proportion': np.cumsum(pcs.explained_variance_ratio_)})
pcsSummary_df = pcsSummary_df.transpose()
pcsSummary_df.columns = ['PC{}'.format(i) for i in range(1, len(pcsSummary_df.columns) + 1)]
pcsSummary_df.round(4)

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17
Standard deviation,2.2773,2.1449,1.0995,1.0336,0.9770,0.8738,0.8041,0.7736,0.7039,0.6629,0.6285,0.5503,0.4388,0.3042,0.2002,0.1745,0.1440
Proportion of variance,0.3044,0.2700,0.0710,0.0627,0.0560,0.0448,0.0380,0.0351,0.0291,0.0258,0.0232,0.0178,0.0113,0.0054,0.0024,0.0018,0.0012
Cumulative proportion,0.3044,0.5745,0.6454,0.7081,0.7642,0.8090,0.8469,0.8821,0.9111,0.9369,0.9601,0.9779,0.9892,0.9946,0.9970,0.9988,1.0000

<b> <font color='purple'> After normalising, to capture 90% of the variance in data, we need to include PC1 to PC9. 
    
  There is a massive drop in the variation explananability starting from PC3. For our purpose, we can consider PC1 to PC9 as the key components since they explain huge chunks of variance (more than 90% together) so we would not be losing out on a lot of information. Increasing the principal components increases variability captured but also increases computational effort and may lead to overfitting, hence we would not be considering PC10, PC11 etc. </font></b>

In [27]:
pcsComponents_df = pd.DataFrame(pcs.components_.transpose(), columns=pcsSummary_df.columns, 
                                index=cleaned_df.columns)
pcsComponents_df.sort_values('PC1',ascending=False)

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17
out-of-state tuition,0.402555,-0.048728,0.051577,0.077658,-0.158499,-0.044407,-0.077965,-0.010688,0.044615,0.151510,-0.099283,-0.507936,-0.101073,0.006317,0.449517,0.507584,-0.175592
in-state tuition,0.379389,-0.150248,0.084350,0.041064,-0.172639,-0.000539,-0.129328,0.009974,0.092325,0.103905,-0.044406,-0.497755,-0.066563,-0.041638,-0.355983,-0.592824,0.157093
% new stud. from top 10%,0.354028,0.093547,-0.120129,-0.372457,0.162260,-0.004445,0.102709,-0.112334,0.028676,-0.326675,0.209275,-0.043489,-0.003825,0.646399,-0.185719,0.168396,0.171236
% new stud. from top 25%,0.340496,0.118396,-0.142720,-0.385565,0.158187,0.092636,0.136409,-0.039927,-0.006007,-0.314110,0.234355,0.010823,0.037524,-0.685605,0.088571,-0.055470,-0.105283
Graduation rate,0.325305,0.024264,-0.181888,-0.012600,0.109137,0.215325,-0.200105,0.389370,0.112811,0.598537,0.353414,0.333592,-0.009703,0.049079,0.006724,0.009623,0.024913
board,0.290437,0.010051,0.252096,0.301620,-0.199067,-0.038477,0.152138,0.466412,0.421339,-0.419434,-0.181506,0.302579,-0.004475,0.001880,-0.011574,0.033039,0.004999
room,0.273165,0.052271,0.250578,0.454416,-0.004482,-0.015068,-0.122402,-0.091329,-0.680595,-0.180139,0.308060,0.153113,-0.120440,0.004846,-0.027487,-0.009710,-0.020306
% fac. w/PHD,0.254201,0.196852,-0.189367,-0.074609,-0.017278,-0.180623,0.533349,0.145009,-0.404837,0.267768,-0.502748,0.096447,0.101835,0.027889,-0.050578,-0.073086,-0.009757
# appli. rec'd,0.078361,0.420164,-0.031982,0.072621,-0.016694,0.112320,-0.268145,-0.093570,0.039628,-0.087361,-0.073021,-0.009995,0.602996,0.198790,0.346774,-0.344637,-0.246354
estim. book costs,0.057302,0.056689,0.652241,-0.044356,0.518644,0.421195,0.190728,-0.130177,0.078975,0.170842,-0.172220,-0.033709,-0.006943,0.009861,-0.004617,0.003225,0.000384
# appl. accepted,0.023659,0.434471,-0.031423,0.118128,-0.089073,0.114381,-0.266285,-0.080991,0.022795,0.035197,-0.166046,-0.062100,0.251257,-0.240232,-0.452347,0.429830,0.392238
add. fees,-0.012351,0.169499,-0.249747,0.446562,0.648920,-0.418437,0.082359,0.048174,0.205132,-0.013333,0.098383,-0.214784,-0.043950,-0.039396,-0.006340,-0.039115,0.030237
# new stud. enrolled,-0.028802,0.445556,-0.038651,-0.031466,-0.075981,0.054079,-0.098870,-0.058138,0.096336,0.019353,-0.072613,0.013719,-0.486306,0.059301,-0.322663,-0.010969,-0.645721
# FT undergrad,-0.049586,0.443583,-0.004012,-0.056459,-0.094781,0.043504,-0.043157,-0.043464,0.034858,-0.009057,-0.061392,0.050779,-0.512673,0.012862,0.441354,-0.217176,0.519944
# PT undergrad,-0.106380,0.287700,0.265769,0.053495,-0.343681,-0.188041,0.509297,-0.122490,0.172351,0.225459,0.531642,-0.107999,0.168015,-0.006459,-0.036556,0.009390,0.003856
estim. personal $,-0.144908,0.156837,0.403735,-0.403709,0.103358,-0.466598,-0.289271,0.505883,-0.194258,0.000128,0.038711,-0.133197,0.051416,-0.013721,-0.012993,0.017390,-0.012251
stud./fac. ratio,-0.278542,0.101034,-0.187598,0.105222,0.003000,0.522154,0.211516,0.525627,-0.207194,-0.181720,0.136107,-0.416236,0.005232,0.065855,-0.006340,0.010918,-0.003511

<b> <font color='purple'> The first principal component measures the balance between tuition fees (out of state and in state) and the student/faculty ratio. It means that if a university has higher tuition fees, it would have a lower student/faculty ratio </font></b>

In [30]:
pcsComponents_df.sort_values('PC2',ascending=False)

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17
# new stud. enrolled,-0.028802,0.445556,-0.038651,-0.031466,-0.075981,0.054079,-0.098870,-0.058138,0.096336,0.019353,-0.072613,0.013719,-0.486306,0.059301,-0.322663,-0.010969,-0.645721
# FT undergrad,-0.049586,0.443583,-0.004012,-0.056459,-0.094781,0.043504,-0.043157,-0.043464,0.034858,-0.009057,-0.061392,0.050779,-0.512673,0.012862,0.441354,-0.217176,0.519944
# appl. accepted,0.023659,0.434471,-0.031423,0.118128,-0.089073,0.114381,-0.266285,-0.080991,0.022795,0.035197,-0.166046,-0.062100,0.251257,-0.240232,-0.452347,0.429830,0.392238
# appli. rec'd,0.078361,0.420164,-0.031982,0.072621,-0.016694,0.112320,-0.268145,-0.093570,0.039628,-0.087361,-0.073021,-0.009995,0.602996,0.198790,0.346774,-0.344637,-0.246354
# PT undergrad,-0.106380,0.287700,0.265769,0.053495,-0.343681,-0.188041,0.509297,-0.122490,0.172351,0.225459,0.531642,-0.107999,0.168015,-0.006459,-0.036556,0.009390,0.003856
% fac. w/PHD,0.254201,0.196852,-0.189367,-0.074609,-0.017278,-0.180623,0.533349,0.145009,-0.404837,0.267768,-0.502748,0.096447,0.101835,0.027889,-0.050578,-0.073086,-0.009757
add. fees,-0.012351,0.169499,-0.249747,0.446562,0.648920,-0.418437,0.082359,0.048174,0.205132,-0.013333,0.098383,-0.214784,-0.043950,-0.039396,-0.006340,-0.039115,0.030237
estim. personal $,-0.144908,0.156837,0.403735,-0.403709,0.103358,-0.466598,-0.289271,0.505883,-0.194258,0.000128,0.038711,-0.133197,0.051416,-0.013721,-0.012993,0.017390,-0.012251
% new stud. from top 25%,0.340496,0.118396,-0.142720,-0.385565,0.158187,0.092636,0.136409,-0.039927,-0.006007,-0.314110,0.234355,0.010823,0.037524,-0.685605,0.088571,-0.055470,-0.105283
stud./fac. ratio,-0.278542,0.101034,-0.187598,0.105222,0.003000,0.522154,0.211516,0.525627,-0.207194,-0.181720,0.136107,-0.416236,0.005232,0.065855,-0.006340,0.010918,-0.003511
% new stud. from top 10%,0.354028,0.093547,-0.120129,-0.372457,0.162260,-0.004445,0.102709,-0.112334,0.028676,-0.326675,0.209275,-0.043489,-0.003825,0.646399,-0.185719,0.168396,0.171236
estim. book costs,0.057302,0.056689,0.652241,-0.044356,0.518644,0.421195,0.190728,-0.130177,0.078975,0.170842,-0.172220,-0.033709,-0.006943,0.009861,-0.004617,0.003225,0.000384
room,0.273165,0.052271,0.250578,0.454416,-0.004482,-0.015068,-0.122402,-0.091329,-0.680595,-0.180139,0.308060,0.153113,-0.120440,0.004846,-0.027487,-0.009710,-0.020306
Graduation rate,0.325305,0.024264,-0.181888,-0.012600,0.109137,0.215325,-0.200105,0.389370,0.112811,0.598537,0.353414,0.333592,-0.009703,0.049079,0.006724,0.009623,0.024913
board,0.290437,0.010051,0.252096,0.301620,-0.199067,-0.038477,0.152138,0.466412,0.421339,-0.419434,-0.181506,0.302579,-0.004475,0.001880,-0.011574,0.033039,0.004999
out-of-state tuition,0.402555,-0.048728,0.051577,0.077658,-0.158499,-0.044407,-0.077965,-0.010688,0.044615,0.151510,-0.099283,-0.507936,-0.101073,0.006317,0.449517,0.507584,-0.175592
in-state tuition,0.379389,-0.150248,0.084350,0.041064,-0.172639,-0.000539,-0.129328,0.009974,0.092325,0.103905,-0.044406,-0.497755,-0.066563,-0.041638,-0.355983,-0.592824,0.157093

<b> <font color='purple'> The second principal component measures the balance between the no of enrolled students (and full time graduates/accepted applicants/received applications) with the tuition fees (out of state and in state). It means that if a university has higher number of enrolled students, its tuition fees would be on the lower side. This is in line with the explanation of PC1 as well. </font> </b>